# Generated by Django 4.2.5 on 2023-12-26 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_payment_orderplaced'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderplaced',
            old_name='payment',
            new_name='payments',
        ),
        migrations.RenameField(
            model_name='orderplaced',
            old_name='product',
            new_name='products',
        ),
    ]
